### PR TITLE
fix errors

### PR DESCRIPTION
**Pull request by MrDemonid**
Helloy!
I found and fixed several errors. For more information, see the file fixerrors.txt.

### CODE REVIEW

**Comment by ogdenpm** [comment]
Andrey

Many thanks for submitting this. I have incorporated the changes mostly as per your submission, with the exceptions noted below. Most of the errors were added due to my semi-automatic porting scripts from the PL/M decompilation. 

 

asm5m.c – the original PL/M which byte matches the original binary, has the while test rather than the do { } while.

 

Loc.h – left unchanged. Whilst there is no harm in setting it to 0xf6c0, the higher value allows for a larger  symbol table with no ill effect.

 

Note for loc4 Microsoft C did not complain about the original code , however I have changed but I kept the strings separated using the cpp concatenation feature i.e. 

byte segNames[] = "ABSOLUTE" "CODE    " "DATA    " "STACK   " "MEMORY  ";

 

Loc7.c alternative change

pageCacheSize = (word)High(outRecordP - (pointer)(pageTab1P = ((page1_t *)(pageTab2P + 256)))) - 1;

this uses pointer scaling to get to the right location.

 

plm4a.c – I left the function named as MiscControl which is in plm6a.c, but added a  parameter to pass in the appropriate txFile reference, for plm4a.c this is &tx1File, for plm6a.c this is &tx2File. This way the common code is still shared.

 

I will do some additional checking, including picking up any outstanding MSVC and gcc warnings and repost to github when complete.

 

Regards

Mark

 

 

From: Andrey Hlus ***@***.***> 
Sent: Friday, April 28, 2023 2:38 PM
To: ogdenpm/c-ports ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ogdenpm/c-ports] fix errors (PR #1)

 

Helloy!
I found and fixed several errors. For more information, see the file fixerrors.txt.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/ogdenpm/c-ports/pull/1


Commit Summary


*	e039485 <https://github.com/ogdenpm/c-ports/pull/1/commits/e0394856be7e1611424575c9fcb615b238c5e2fe>  fix errors


File Changes 


(16 <https://github.com/ogdenpm/c-ports/pull/1/files>  files)

*	M asm80/asm3m.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-3e2a9b3fd36a90dfd6706a0911bb0151f78950606233edf8e0179543dabd3c73>  (4) 
*	M asm80/asm5m.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-51370acac5efcfcf3df1031fa68c7dcfc7612dbe16bc5cd616d3ea4265667ffa>  (4) 
*	A asm80/fiexerrors.txt <https://github.com/ogdenpm/c-ports/pull/1/files#diff-5fb0b11210f915fe0787217d3c4722229fa5c053230aa1101d9018f596a142e6>  (103) 
*	M asm80/startm.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-531a7f19141ac6d63dd0cf01138b39d06eef7f0e42391b06a1dd5146b8365725>  (4) 
*	A link/fiexerrors.txt <https://github.com/ogdenpm/c-ports/pull/1/files#diff-72de209a218125a0ddb4881c42bcbca7535123e1742c0e6e638c243448852015>  (23) 
*	M link/linkov.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-c8d0d2f262e5beca926c023912fba0e7bd82637d7eeb5094f0670a5e10d4064d>  (2) 
*	A locate/fiexerrors.txt <https://github.com/ogdenpm/c-ports/pull/1/files#diff-bb55cf727a94b5f140d39e8c94416765e669d8779b9c9e837c7480b37ec04ef3>  (148) 
*	M locate/loc.h <https://github.com/ogdenpm/c-ports/pull/1/files#diff-e040d7cb58ab17775dcc92cd5c93a2230029071acd49763885872b41b8615457>  (2) 
*	M locate/loc1.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-c42d4d1cc6279885e6de86585f920d4bd1817644985b8d2bcb4c4e22f46a91a3>  (2) 
*	M locate/loc4.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-a6af4fdbdb0ee0f78d9850104a715f7c13d3e647cfe9d416f95adcd8a1e5d905>  (4) 
*	M locate/loc7.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-56b2d1e34224843197a118dd4cf7eb2792ff6cb75f6f5d50bf6b38ef657c5f7c>  (5) 
*	A plm80c/fiexerrors.txt <https://github.com/ogdenpm/c-ports/pull/1/files#diff-ce269553714c48408af400698eb2d633600ebf5cb707276bf0450e67638b3a89>  (173) 
*	M plm80c/io.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-154faf25047c12a9c5ac9f52a350cee50fec8f33571e61096f9afcf272df3fe5>  (2) 
*	M plm80c/main4.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-30da6f1bd541622ead9e2265b13fd551521d6f44fd4afcdefd86e630f58d6d68>  (1) 
*	M plm80c/plm0b.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-fba4ef51a389bc085f913a114f195b4591cf437e0b89d42cc5002df19119f8fe>  (2) 
*	M plm80c/plm4a.c <https://github.com/ogdenpm/c-ports/pull/1/files#diff-d00815e9ac7b62bd77c74b4e0bf6d389554a68a20c29f6d22ce81eb6d2a36abf>  (34) 


Patch Links:


*	https://github.com/ogdenpm/c-ports/pull/1.patch
*	https://github.com/ogdenpm/c-ports/pull/1.diff

**Comment by MrDemonid** [comment]
Hello Mark!

asm5m.c

On PL/M:
----------
        entryOffset = 0;    /* offset to current symbol to compare */
                    /* offset of first to use - hashes packed symbol name */
        deltaToNext = **symTab(TID$KEYWORD)** + ((packedTok(0) + packedTok(1)) mod 151) * 8;
        do while deltaToNext <> 0;    /* while not end of chain */

deltaToNext = symTab(TID$KEYWORD) + (0xA528 mod 151)*8 = symTab(TID$KEYWORD) 
**deltaToNext > 0**!!!
^^^^^^^^^^

On C:
-----
        entryOffset = symTab[TID_KEYWORD]; /* offset to current symbol to compare */
        deltaToNext = ((packedTokP[0] + packedTokP[1] & 0xffff)) % 151;// index on array
        while(deltaToNext != 0);

deltaToNext = ((packedTokP[0] + packedTokP[1] & 0xffff)) % 151;
deltaToNext = (0xA528 + 0) % 151;
**deltaToNext == 0**!!!
^^^^^^^^^^^
-------------------------------------------
Here, either change the cycle, or do so:
        entryOffset = 0; ; /* offset to current symbol to compare */
        deltaToNext = symTab[TID_KEYWORD] + ((packedTokP[0] + packedTokP[1] & 0xffff)) % 151;

Otherwise, the program will give an error. Exanple:
  0005               20   AUTOSPD       equ 5
                     21 
                     22 
                     23 ;------------------------------------------------------------------------
                     24 ; Init keyboard driver
                     25 ;------------------------------------------------------------------------
                     26 KbInit:
E 0000               27     IF AUTOSPD NE 5
 (   0)
  0000 00            28         nop
                     29     ENDIF


=================================================================
loc.h
Ok.

=================================================================
loc4.c

Open Watcom is buggy?

=================================================================
loc7.c

I don't know what WATCOM will generate.
Okay, I agree.

=================================================================
plm4a.c

Ok.

**Comment by ogdenpm** [comment]
Andrey

Now I understand, I forgot to account for deltaToNext not being initially offset.

 

Note I am part way through making the build clean for gcc. So far found an additional error in asm80 and quite a few clean up items, mostly about warnings on signed/unsigned and recommendations to insert parentheses around assignments in conditional statements, or make complex precedence clearer.

Regards

Mark

**Comment by MrDemonid** [comment]
gcc - it's good.

Best Regards!
Andrey.

**Comment by ogdenpm** [comment]
Andrey

I have posted an update. Major changes

*	In addition to your fixes I have fixed several others identified during making the compilations clean using gcc warn all. It is also clean with MSVC /W3. Whilst /W4 has additional warnings, I have checked them. Since most are warnings about potential loss of information when larger ints  are assigned to smaller one, I have decided not to put lots of casts in to eliminate them. Interestingly MSVC /Wall has lots of informational messages not just warnings, e.g. in-lining decisions.
*	Added a Linux build suite and made tex work under Linux. Requires perl and gnu make.
*	The tools should now work with non le endian processors.
*	I added my new version model across all the applications.
*	Licence conditions change to reflect original owners and that the code is for hobbyist use and academic interest. 

 

There was an interesting bug in that the optimising compiler swapped the order of calculation with an & operation. This is fine by the standards but caused an unexpected error in processing. It is an example of sequence point issues, some additional ones were identified by gcc -Wall and were also fixed.

 

Regards

Mark

**Comment by MrDemonid** [comment]
It's clear.
This compiler is not only of academic interest. My hobby in my spare time is microcontrollers and microcomputers based on Intel 8080. I have made small changes to this compiler (https://github.com/MrDemonid/PL-M-80-Tools). Several PL/M programs are in my repository (AY Player , Image Viewer and two games - Dvigalka and Bolder Dash).
By the way, my last game - Bolder Dash, is available in two versions - in PL/M and in C (Z88DK). The PL/M compiler generates code 50-70% more compact than a modern C compiler. There used to be real programmers, not like the current ones.

**Comment by ogdenpm** [comment]
Andrey
Note the tools allow the Isis paths to be set using ISIS_Fx=path environment variables.
I usually use the original tools with my enhanced emulator. It supports auto mapping of directories in addition to environment variables, temporary paths are handled to allow parallel application usage. I also added a Perl wrapper for asm80 to support long names and structures.
Long command lines are supported and auto convert to use & continuation. Redirection from a file to stdin works for extended command lines.
The core functionality is implemented in my version of thames.

Note lib, link and locate may need adjusting to support some of the changes e.g. _ in a name.

As to copyright the original owner is still Intel, the porting and the earlier reverse engineering is my own work.
Regards
Mark Ogden
________________________________

**Comment by MrDemonid** [comment]
At first I wanted to make a preprocessor. But, this method has one drawback - difficult debugging of the application. If I have a var_LongName variable in my program, then the preprocessor will give it a different name and this is confusing. In this case, you also need to create a postprocessor to correct debug files. In the end, I decided that it was easier to make changes to the compiler itself.
LIB, LINK and LOCATE do not require adjustment for the '_' character.
I do not speak English well, so it is difficult for me to write correct copyrights. If something is wrong, then correct me, I will make the necessary changes.

**Comment by ogdenpm** [comment]
Andrey
My Perl wrapper does post processing to fix the code back. It also reformats the symbol table
Matk

Regards
Mark Ogden
________________________________

**Pull request closed without merging**
